#[cfg(feature = "anthropic")]
pub mod anthropic;
pub mod anthropic_telemetry;
#[cfg(feature = "bedrock")]
pub mod bedrock;
#[cfg(feature = "cloud")]
pub mod cloud;
#[cfg(feature = "copilot_chat")]
pub mod copilot_chat;
#[cfg(feature = "deepseek")]
pub mod deepseek;
#[cfg(feature = "google")]
pub mod google;
#[cfg(feature = "lmstudio")]
pub mod lmstudio;
#[cfg(feature = "mistral")]
pub mod mistral;
#[cfg(feature = "ollama")]
pub mod ollama;
pub mod open_ai;
pub mod open_ai_compatible;
#[cfg(feature = "open_router")]
pub mod open_router;
#[cfg(feature = "opencode")]
pub mod opencode;

pub mod qwen;
#[cfg(feature = "vercel")]
pub mod vercel;
#[cfg(feature = "vercel_ai_gateway")]
pub mod vercel_ai_gateway;
#[cfg(feature = "x_ai")]
pub mod x_ai;
